name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: shellcheck unrarall tests/test.sh tests/test-five.sh

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [unrar]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y unrar rar
      - name: Run tests
        run: |
          tests/test.sh
          tests/test-five.sh
